export type ResponsesScenario = {
  readonly id: string;
  readonly label: string;
  readonly hint: string;
  readonly runner: "uv" | "bun";
  readonly script: string;
  readonly scenario?: string;
};

export const responsesScenarios: readonly ResponsesScenario[] = [
  {
    id: "create-text",
    label: "01 — Texte simple",
    hint: "POST JSON et réponse finale",
    runner: "uv",
    script: "responses/test_create_text.py",
  },
  {
    id: "stream",
    label: "02 — Streaming",
    hint: "Événements SSE et texte progressif",
    runner: "uv",
    script: "responses/test_stream.py",
  },
  {
    id: "history",
    label: "03 — Historique explicite",
    hint: "Deux tours fournis par le client",
    runner: "uv",
    script: "responses/test_history.py",
  },
  {
    id: "previous-response",
    label: "04 — previous_response_id",
    hint: "Continuité native, sans historique répété",
    runner: "uv",
    script: "responses/test_lifecycle.py",
    scenario: "previous-response",
  },
  {
    id: "conversation",
    label: "05 — Conversation",
    hint: "Continuité par identifiant de conversation",
    runner: "uv",
    script: "responses/test_lifecycle.py",
    scenario: "conversation",
  },
  {
    id: "retrieve",
    label: "06 — Lecture",
    hint: "Lire une réponse et ses input items",
    runner: "uv",
    script: "responses/test_lifecycle.py",
    scenario: "retrieve",
  },
  {
    id: "delete",
    label: "07 — Suppression",
    hint: "Supprimer puis relire la réponse créée",
    runner: "uv",
    script: "responses/test_lifecycle.py",
    scenario: "delete",
  },
  {
    id: "background-cancel",
    label: "08 — Background et annulation",
    hint: "Cycle de vie natif et cancel public",
    runner: "uv",
    script: "responses/test_lifecycle.py",
    scenario: "background-cancel",
  },
  {
    id: "input-tokens",
    label: "09 — Comptage de tokens",
    hint: "Compteurs retournés par l’amont",
    runner: "uv",
    script: "responses/test_lifecycle.py",
    scenario: "input-tokens",
  },
  {
    id: "compact",
    label: "10 — Compaction",
    hint: "Continuité après compaction native",
    runner: "uv",
    script: "responses/test_lifecycle.py",
    scenario: "compact",
  },
  {
    id: "websocket",
    label: "11 — WebSocket",
    hint: "Frames Responses et second tour",
    runner: "bun",
    script: "responses/test_websocket.ts",
  },
  {
    id: "node-sdk",
    label: "12 — SDK Node",
    hint: "Client OpenAI Node contre le proxy",
    runner: "bun",
    script: "responses/test_node.ts",
  },
  {
    id: "instructions",
    label: "13 — Instructions",
    hint: "Omis, null et valeur explicite",
    runner: "uv",
    script: "responses/features.py",
    scenario: "instructions",
  },
  {
    id: "parameters",
    label: "14 — Paramètres",
    hint: "Paramètres de génération et verbosité",
    runner: "uv",
    script: "responses/features.py",
    scenario: "parameters",
  },
  {
    id: "json-object",
    label: "15 — JSON object",
    hint: "Sortie JSON structurée",
    runner: "uv",
    script: "responses/features.py",
    scenario: "json-object",
  },
  {
    id: "json-schema",
    label: "16 — JSON Schema",
    hint: "Sortie conforme au schéma",
    runner: "uv",
    script: "responses/features.py",
    scenario: "json-schema",
  },
  {
    id: "function",
    label: "17 — Fonction",
    hint: "Aller-retour function_call",
    runner: "uv",
    script: "responses/features.py",
    scenario: "function",
  },
  {
    id: "tool-choice",
    label: "18 — tool_choice",
    hint: "Sélection explicite d’outil",
    runner: "uv",
    script: "responses/features.py",
    scenario: "tool-choice",
  },
  {
    id: "parallel-tools",
    label: "19 — Outils parallèles",
    hint: "Appels d’outils multiples",
    runner: "uv",
    script: "responses/features.py",
    scenario: "parallel-tools",
  },
  {
    id: "reasoning-replay",
    label: "20 — Raisonnement",
    hint: "Reprise d’item de reasoning",
    runner: "uv",
    script: "responses/features.py",
    scenario: "reasoning-replay",
  },
  {
    id: "cache",
    label: "21 — Cache",
    hint: "Paramètres de cache de prompt",
    runner: "uv",
    script: "responses/features.py",
    scenario: "cache",
  },
  {
    id: "image",
    label: "22 — Image",
    hint: "Entrée image contrôlée",
    runner: "uv",
    script: "responses/features.py",
    scenario: "image",
  },
  {
    id: "builtins",
    label: "23 — Outils natifs",
    hint: "Web search, fichiers, code et MCP",
    runner: "uv",
    script: "responses/features.py",
    scenario: "builtins",
  },
  {
    id: "native-media",
    label: "24 — Fichier en entrée",
    hint: "Fichier data URL inline",
    runner: "uv",
    script: "responses/features.py",
    scenario: "native-media",
  },
  {
    id: "store-json",
    label: "25 — Stockage JSON",
    hint: "store:true, lecture, input items et nettoyage",
    runner: "uv",
    script: "responses/test_lifecycle.py",
    scenario: "store-json",
  },
  {
    id: "web-search",
    label: "26 — Recherche web",
    hint: "Alias preview, appel réel et citation",
    runner: "uv",
    script: "responses/features.py",
    scenario: "web-search",
  },
] as const;

export const responsesScenarioIds = responsesScenarios.map(({ id }) => id);
